# 公共配置文件
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.50.129:3306/api
    username: root
    password: 123456
  # redis 配置
  redis:
    port: 6379
    host: 192.168.50.129
    database: 0
# 这段配置仅供测试，实际应该根据登录用户获取对应的 ak、sk
api:
  client:
    access-key: wsj
    secret-key: abcdefgh
dubbo:
  application:
    name: dubbo-springboot-demo-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://192.168.50.129:8848
